### ISSUE TITLE
Unterminated string

### ISSUE THREAD

**Issue by freelancertexas** [tduyduc/lol-teamfight-tactics-assist#1]
so, i just get this every single time i try to execute the file. The one before the surrender buttons changed places still works besides the obvious no surrendering issue.
![errrr](https://user-images.githubusercontent.com/71916827/94330909-e29bd300-ff9e-11ea-895e-b267d64666cc.png)

**Comment by tduyduc** [comment]
Hi, thanks for reporting the issue.

It is very likely that your downloaded file is corrupted, since the file on this repository doesn't have those HTML tags like the screenshot. You might want to download the repository again (just to be sure) or download the source code (or the compiled executable file) from the releases section.

If the file is identical to the one on the repository, it should run without this ominous error. :D 

Thanks!
